### ISSUE TITLE
Specify minimum Python version

### ISSUE THREAD

**Issue by mc-mario** [signalkraft/myPyllant#1]
Good morning!

I tried running the tests but I was getting the following error;
```python3
  File "/Users/-/GitHub/myPyllant/tests/generate_test_data.py", line 31, in main
    from myPyllant.api import API_URL_BASE, MyPyllantAPI
  File "/Users/-/GitHub/myPyllant/src/myPyllant/api.py", line 10, in <module>
    from myPyllant.models import (
  File "/Users/-/GitHub/myPyllant/src/myPyllant/models.py", line 58, in <module>
    class Zone(BaseModel):
  File "/Users/-/GitHub/myPyllant/src/myPyllant/models.py", line 69, in Zone
    humidity: float | None
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

After some digging I found this is due to[ `|` operator being a Python 3.10](https://github.com/tiangolo/typer/issues/371#issuecomment-1073649190) feature, and I was running it with Python 3.9 ([as hinted here](https://github.com/signalkraft/myPyllant/blob/2addbdcbc2bc71ab416a874e091c72981adf812b/setup.cfg#L57) in the setup.cfg)

Do you mind specifying the supported Python version somewhere? 

Very cool project!

**Comment by signalkraft** [comment]
Thanks, I added a note in the README and changed the two remaining places where 3.9 was mentioned.
