### ISSUE TITLE
ERROR TWO DAYS AGO

### ISSUE THREAD

**Issue by gbarrena** [signalkraft/myPyllant#10]
It hasn't connected to the system for two days and it gives these errors.

Este error se originó a partir de una integración personalizada.

Logger: custom_components.mypyllant
Source: custom_components/mypyllant/__init__.py:179
Integration: myVAILLANT (documentation, issues)
First occurred: 12:12:06 (1 occurrences)
Last logged: 12:12:06

Unexpected error fetching myVAILLANT data: 1 validation error for Zone heating_state value is not a valid enumeration member; permitted: 'IDLE', 'HEATING_UP' (type=type_error.enum; enum_values=[<ZoneHeatingState.IDLE: 'IDLE'>, <ZoneHeatingState.HEATING_UP: 'HEATING_UP'>])
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mypyllant/__init__.py", line 179, in _async_update_data
    async for system in await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.11/site-packages/myPyllant/api.py", line 227, in get_systems
    system = System(
             ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/myPyllant/models.py", line 123, in __init__
    self.zones = [Zone(system_id=self.id, **z) for z in self._raw_zones]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/myPyllant/models.py", line 123, in <listcomp>
    self.zones = [Zone(system_id=self.id, **z) for z in self._raw_zones]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Zone
heating_state
  value is not a valid enumeration member; permitted: 'IDLE', 'HEATING_UP' (type=type_error.enum; enum_values=[<ZoneHeatingState.IDLE: 'IDLE'>, <ZoneHeatingState.HEATING_UP: 'HEATING_UP'>])

**Comment by gbarrena** [comment]
I have detected that the error occurs when activating the cooling floor, not the underfloor heating.

I think that some variable is not declared to show the refreshing soil

**Comment by signalkraft** [comment]
Thanks for the report, the latest release should fix this

**Comment by gbarrena** [comment]
Thanks!
