### ISSUE TITLE
Test data from my heat pump

### ISSUE THREAD

**Issue by rmalbrecht** [signalkraft/myPyllant#30]
Hi,

I'm using the home assistant integration. Great work, thanks for developing this.

I dumped the test_data from our heat pump. It's s simple installation, nothing funky.

The myVaillant app can show the start/stops for pump and hydraulics. Have you seen them in the API-resonse? I would love to have them in home assistant.
[test_data.zip](https://github.com/signalkraft/myPyllant/files/13216681/test_data.zip)

Regards,
Robert

**Comment by signalkraft** [comment]
Thanks for the test data - no, I haven't seen that. Can you point out where in the app you can see this info?

**Comment by signalkraft** [comment]
Interesting, I don't see that in my setup. But my energy stats are also currently broken. It's also not part of your test data, so it's probably coming from a different endpoint.

If you've got the time you could try and [reverse engineer the API calls](https://dev.to/sudo_overflow/reverse-engineering-a-private-api-with-mitm-proxy-20ia). I'd be happy to add the information, if you can find it in the API calls somewhere.

**Comment by signalkraft** [comment]
Related: https://github.com/signalkraft/myPyllant/issues/33

I'll keep the discussion going there, since that issue included the (potential) endpoint.
