### ISSUE TITLE
Amount of Cycles aroTherm

### ISSUE THREAD

**Issue by maiksensi** [signalkraft/myPyllant#33]
Hey 👋 ,
is there any chance the amount of cycles could be added as an entity? Problem is, I tried to setup mitm with IOS and my MAC but the certificate pinning prevents me from posting the correct API. The MyVaillant app can show the amount of cycles and working hours. The API seems to be something like this (which I only found because they use instana as an observability solution): `https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/hem/SOME-ID-NOT-SURE-IF-SENSITIVE/mpc`

**Comment by signalkraft** [comment]
I've added the endpoint to the export and generate test data scripts in the latest version on the main branch in this repo. Could you [generate test data](https://signalkraft.com/mypyllant-component/3-contributing/#contributing-test-data) and send it to me? It should already be anonymized.
