### ISSUE TITLE
Additional Properties

### ISSUE THREAD

**Issue by electricfire** [signalkraft/myPyllant#45]
Hi thanks for this module, I was wondering are you able to retrieve additional parameters like flowrate and the return flow temp?  Also I can see the heat curve setting but cannot change it, is it possible so that it can be changed.  I have the arotherm heatpump.  Appreciate your feedback

**Comment by signalkraft** [comment]
You can try the export and generate test data commands to get the raw data. If you can't find the data in there, it's likely not getting reported by the API.

As for changing values, if it's not possible through the app I can't implement it with this library. AFAIK heat curve can't be updated through the app.
