### ISSUE TITLE
Failure to Install on Raspberry Pi 4B

### ISSUE THREAD

**Issue by phethuk** [signalkraft/myPyllant#46]
I cannot install on my Raspberry Pi 4B. (Rasbian) I get:

pi@raspberrypi:~ $ pip install myPyllant
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting myPyllant
  Could not find a version that satisfies the requirement myPyllant (from versions: )
No matching distribution found for myPyllant

Annoyingly, I did install successfully on my Android tablet (as a test)!

**Comment by signalkraft** [comment]
Could you post the output of `pip --version`? If you have git installed, you can install directly from Github: `pip install git+https://github.com/signalkraft/myPyllant.git`

**Comment by phethuk** [comment]
Thanks.

pi@raspberrypi:~ $ pip --version
pip 18.1 from /usr/lib/python2.7/dist-packages/pip (python 2.7)

**Comment by signalkraft** [comment]
You need a newer version of python3, maybe try pip3 instead of pip.

**Comment by phethuk** [comment]
Thank you very much. pip3 was the answer and now to try to communicate with my system.
