### ISSUE TITLE
sending commands via command line using docker

### ISSUE THREAD

**Issue by lightfield1** [signalkraft/myPyllant#58]
great work so far! :-)
Using the following command line to get system information works fine for me:
```
docker run -ti ghcr.io/signalkraft/mypyllant:latest python3 -m myPyllant.export myUser myPassword vaillant --country germany
```
but (and sorry for this question) I wasn't able to manage sending commands. I tried e.g.:
```
docker run -ti ghcr.io/signalkraft/mypyllant:latest python3 -m myPyllant.api.set_zone_heating_operating_mode myUser myPassword vaillant --country germany --zone Wohnzimmer --mode NIGHT
```
maybe it's because im not that familiar with python. I would be very happy if you could give me the correct prompt for the obviously wrong example above.

**Comment by signalkraft** [comment]
Docker can only run certain pre-defined commands (export, generate_test_data & report).

You need to write a Python script to call `set_zone_heating_operating_mode`, or use the Python REPL. Check out the sample in the README for a starting point.
