### ISSUE TITLE
set_dhw_circulation_time_program doesn´t work

### ISSUE THREAD

**Issue by DanielSoftwareDev** [signalkraft/myPyllant#66]
Hi,
i tried the service to set the time_programm to my circulation_pump. After push the button (response "green") but no data was change. I waited some minutes but nothing changed.
can u help me a bit?

**Comment by signalkraft** [comment]
Please [open an issue for the home assistant component](https://github.com/signalkraft/mypyllant-component/issues/new/choose) and provide logs, I can't help you without detailed information.
