### ISSUE TITLE
cannot log-in into the integration

### ISSUE THREAD

**Issue by AlexAhrens** [signalkraft/myPyllant#7]
once I enter my credentials and hit send, it saves, than deletes the credentials and nothing happens. does anyone have a clue where to look at why the home assistant integration behaves that way?

**Comment by joselaya** [comment]
The same thing happens to me :-( 
Any Help?

**Comment by GieBek** [comment]
The same thing happens to me :-(

**Comment by MP14588** [comment]
I have the same problem. I'm stucked in the login pop-up page titled "Same as myVAILLANT app". I fill the fields with username and password but nothing happens....only pop-up refresh with empty field. Cheers.

**Comment by signalkraft** [comment]
Vaillant changed the authentication completely. They went from Okta to a Keycloak instance, the latest version has experimental support for that.

Let me know if it works for you all!

**Comment by Alllfff** [comment]
> Vaillant changed the authentication completely. They went from Okta to a Keycloak instance, the latest version of this library has experimental support for that.
> 
> Let me know if it works for you all! Token refreshing should work, but it's not tested

sorry for a newbie question, but how do i try the experimental support? which is the latest version?

**Comment by signalkraft** [comment]
https://github.com/signalkraft/mypyllant-component/issues/4 let's continue there.
